### ISSUE TITLE
Error in UnionOfRowsOp when using WeakDirectSumDecomposition

### ISSUE THREAD

**Issue by Tschitschibor** [homalg-project/CatReps#4]
gap> etas := WeakDirectSumDecomposition( fortyone );;
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `UnionOfRowsOp' on 2 arguments at /home/user/gap-4.10.2/lib/methsel2.g:250 called from
UnionOfRowsOp( arg, arg[1] ) at /home/user/.gap/pkg/homalg_project/Gauss/gap/GaussDense.gi:503 called from
UnionOfRows( result.coeffs, result.relations
 ) at /home/user/.gap/pkg/homalg_project/GaussForHomalg/gap/GaussFQI.gi:80 called from
RP!.RowReducedEchelonForm( M, T
 ) at /home/user/.gap/pkg/homalg_project/MatricesForHomalg/gap/Service.gi:203 called from
RowReducedEchelonForm( M, TT
 ) at /home/user/.gap/pkg/homalg_project/MatricesForHomalg/gap/Service.gi:2288 called from
BasisOfRowsCoeff( B, C ) at /home/user/.gap/pkg/homalg_project/MatricesForHomalg/gap/Service.gi:2566 called from
...  at *stdin*:1
type 'quit;' to quit to outer loop

**Comment by zickgraf** [comment]
This is probably the result of https://github.com/homalg-project/homalg_project/pull/317 which replaced `UnionOfRowsOp` by `UnionOfRows` (mostly). However, I cannot reproduce the issue. Could you enter a break loop before line 80 in `/home/user/.gap/pkg/homalg_project/GaussForHomalg/gap/GaussFQI.gi` and check if `result.coeffs` and `result.relations` are sparse matrices? Or alternatively provide more code to reproduce the issue?

**Comment by Tschitschibor** [comment]
I checked, and both arguments were not sparse matrices. They are

brk> arg;
[ [ [ Z(3)^0, 0*Z(3), Z(3)^0 ], [ Z(3)^0, 0*Z(3), 0*Z(3) ], [ 0*Z(3), Z(3)^0, 0*Z(3) ] ], [  ] ]

brk> arg[1];
[ [ Z(3)^0, 0*Z(3), Z(3)^0 ], [ Z(3)^0, 0*Z(3), 0*Z(3) ], [ 0*Z(3), Z(3)^0, 0*Z(3) ] ]

Maybe the problem with sparse matrices lies at line 30 of our example where we had 
HOMALG_MATRICES.PreferDenseMatrices := true;

which was needed in line 138 of CatRepsWithCAP.gi with Eval( UnderlyingMatrix( a ) )!.matrix

To reproduce the issue maybe run the whole example from

~/.gap/pkg/catreps/examples$ gap ConcreteCategoryWithEndomorphismGroups.g

**Comment by zickgraf** [comment]
Now I understand, thanks for the details!

When refactoring the code I had to guess the data type of `result.coeffs` and `result.relations`, and the tests in `GaussForHomalg` only include an example where they are sparse matrices.

I will discuss with @mohamed-barakat later if we want to include a method `UnionOfRowsOp` for `IsList, IsList` again (which might be dangerous because of the rather unspecific `IsList` filter) or if we want to handle the case of dense matrices separately.

Until then you can downgrade `homalg_project` to https://github.com/homalg-project/homalg_project/commit/22c953d0db41f9f770b98ce8f47fc8d829f5bed4 to prevent the error.
